//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtnews.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rtnews.Strings.StringTable", typeof(StringTable).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 己阅读： 的本地化字符串。
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值班领导 的本地化字符串。
        /// </summary>
        internal static string DutyLeader {
            get {
                return ResourceManager.GetString("DutyLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值班科室 的本地化字符串。
        /// </summary>
        internal static string LeaderPart {
            get {
                return ResourceManager.GetString("LeaderPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要闻详情 的本地化字符串。
        /// </summary>
        internal static string News0 {
            get {
                return ResourceManager.GetString("News0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知详情 的本地化字符串。
        /// </summary>
        internal static string News1 {
            get {
                return ResourceManager.GetString("News1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态详情 的本地化字符串。
        /// </summary>
        internal static string News2 {
            get {
                return ResourceManager.GetString("News2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上高公安 的本地化字符串。
        /// </summary>
        internal static string NewsName {
            get {
                return ResourceManager.GetString("NewsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，没有获取到数据 的本地化字符串。
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据刷新出错，请检查一下网络 的本地化字符串。
        /// </summary>
        internal static string RefreshError {
            get {
                return ResourceManager.GetString("RefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间： 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公安要闻 的本地化字符串。
        /// </summary>
        internal static string Title0 {
            get {
                return ResourceManager.GetString("Title0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知通报 的本地化字符串。
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局动态 的本地化字符串。
        /// </summary>
        internal static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日值班 的本地化字符串。
        /// </summary>
        internal static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
    }
}
